name: cicd test

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # jdk setting
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # gradle build
      - name: Test with Gradle
        run: |
          cd ./our-memory
          ./gradlew test

      - name: Build with Gradle
        run: |
          cd ./our-memory
          ./gradlew build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./our-memory
          file: ./our-memory/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/memory-test:latest
          platforms: linux/arm64

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
